path replacement DRY
peter-gribanov/clean-code-php pull request #40
Opened 2023-02-18 19:46 UTC by ispopov

2023-02-20 15:26 UTC, peter-gribanov requested changes

2023-02-20 15:26 UTC, peter-gribanov commented on README.md
> +[*Чистый код*](https://www.livelib.ru/book/1000770866-chistyj-kod-sozdanie-analiz-i-refaktoring-biblioteka-programmista-robert-martin) Роберта Мартина и
Поставьте лучше ссылку на Лабиринт
https://www.labirint.ru/books/642466/

2023-02-20 17:08 UTC, ispopov commented on README.md
> +[*Чистый код*](https://www.livelib.ru/book/1000770866-chistyj-kod-sozdanie-analiz-i-refaktoring-biblioteka-programmista-robert-martin) Роберта Мартина и
Поставил

2023-02-21 07:19 UTC, peter-gribanov approved these changes

2023-02-21 07:19 UTC, merged

2023-02-21 07:19 UTC, peter-gribanov commented
Спасибо за работу :+1: